kcp-dev/kcp-glbc

utils/local-setup.sh
The cluster controller is already running in kcp when you use `--run-controllers` option, and running a second instance appears to causes issues syncing resources back to kcp.
=> Remove cluster controller startup from local-setup

pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go
Split the Ingress reconciliation method into `reconcileLeaf` and `reconcileRoot`. Add logic to select which method to use based on the Ingress object to be reconciled.
=> refactor: Split Ingress reconcile into two methods

cmd/ingress-controller/main.go, go.mod, go.sum, pkg/dns/aws/dns.go, pkg/dns/dns.go, pkg/reconciler/dns/controller.go, pkg/reconciler/dns/dns_record.go, pkg/util/slice/slice.go, samples/dnsrecord.yaml, samples/echo-service-single-cluster/ingress.yaml
Implements the dns controller to reconcile records into a route53 zone.
Requires the following env vars to be set locally before running the controller:
```
AWS_ACCESS_KEY_ID=<my aws access key id>
AWS_SECRET_ACCESS_KEY=<my aws secret access key>
AWS_DNS_PUBLIC_ZONE_ID=<route53 zone id>
```
=> AWS DNS record creation

samples/echo-service-multi-cluster/echo.yaml, samples/echo-service-multi-cluster/ingress.yaml, samples/echo-service-single-cluster/echo.yaml
Update the cluster label names (a -> 1, b -> 2) required since
local-setup changes https://github.com/Kuadrant/kcp-glbc/pull/16
=> Fix sample deployments

cmd/ingress-controller/main.go, go.mod, go.sum, pkg/net/hostresolv.go, pkg/net/watch.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go
> Link to JIRA: https://issues.redhat.com/browse/HCG-33
Add ability for the controller to keep track of the current host -> IP mappings and notify the Ingress reconciler if there's any changes. The reconciler will propagate the changes to the DNSRecord.
To verify locally, a [`ConfigMapHostResolver`](https://github.com/Kuadrant/kcp-glbc/pull/19/files#diff-7078f0862820391d59c2ad9da6fbce41aaebbcba849902bee0010bd219f2f329R47-R51) is available. Selecting that resolver:
1. Run KCP and the Ingress controller
2. Create a ConfigMap with the expected hosts. Example
```yaml
apiVersion: v1
data:
3806265934.hcpapps.net: '[{"IP": "1.1.1.1","TTL":30}, {"IP": "12.12.12.12","TTL":30}]'
my-hostname.hcpapps.net: '[{"IP":"2.2.2.2","TTL":60}]'
kind: ConfigMap
metadata:
clusterName: admin
creationTimestamp: …
```
=> HCG-33: Ability to track changes in hostname IPs

.github/workflows/ci.yaml, .golangci.yaml, Makefile, go.mod, go.sum, hack/tools.go
**Update Makefile**
* Organise Makefile to be more like a kubebuilder generated file.
* Add make targets, help, fmt, vet, verify-generate, docker-build(Not implemented) and test(Not implemented).
* Remove duplicate go-get-tool definition.
* Adds a new make target to run golangci-lint `make lint` and a golangci config that is configured to run the default linters plus format checks (gofmt) https://golangci-lint.run/usage/configuration/.
**Add CI GitHub Workflow**
Adds a github action workflow to run basic CI checks on pull requests and any updates made directly to main. Current checks are `lint` which runs golangci-lint, `codegen` which checks all generated files are correct and `test`  which runs `make test` (Not currently implemented).
Note, the lint action is expected to fail on main …
=> Add basic ci checks

pkg/reconciler/ingress/ingress.go
The ingress controller on the clusters might not always specify a hostname for the load balancers. Add a check to skip host watching if no hostname is specified
=> fix: Skip host watching when no hostname

.github/workflows/kcp-glbc-image.yaml, Dockerfile, Makefile
* Add Dockerfile
* Add target to makefile for docker-build (dev use only)
* Add GitHub action to build and publish image to quay.io. Publishes images for any branch or tag pushed to the repo (not PRs), adds tags: short commit hash (git rev-parse --short HEAD), ref_name (branch/tag name) and latest (main branch only).
Run of this branch (pushed to "kuadrant" rather than my fork to test): https://github.com/Kuadrant/kcp-glbc/actions/runs/1981111707
Quay repo: https://quay.io/repository/kuadrant/kcp-glbc?tab=tags
Test the image locally with:
```
docker run --rm --network="host" -u $UID -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DNS_PUBLIC_ZONE_ID=$AWS_DNS_PUBLIC_ZONE_ID -e HCG_LE_EMAIL=$HCG_LE_EMAIL -v "$(pwd)/.kcp":/.kcp:z -v …
```
=> Add image build

cmd/ingress-controller/main.go, pkg/cluster/mapper.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go
This PR adds a policy to allow the creation of custom hosts by setting a flag `-enable-custom-hosts` to the ingress controller, if the flag is not set any custom hosts defined in the ingress object will be replaced to the ingress generated host, this policy is required to prevent custom hosts from being used at workspace level so traffic can't be stolen from a particular domain.
>Any replaced host will be reported via the annotation `kuadrant.dev/custom-hosts.replaced` 
TODO: TLS might need to be changed to use the cert created for the generated host
1. Run the ingress controller with the `-enable-custom-hosts` set to false
```bash
./bin/ingress-controller -kubeconfig .kcp/admin.kubeconfig -enable-custom-hosts=false -dns-provider fake
```
2. Create an ingress object using a different host …
=> Allows to prevent custom hosts from being used

README.md, utils/local-setup-add-crc-cluster.sh, utils/local-setup.sh
Adds a local setup script that will create and add a crc cluster to your
local kcp cluster. Requires crc installed locally see
https://console.redhat.com/openshift/create/local
When adding different clusters it seems that the version of kubernetes
needs to be consistent across all physical clusters in order for
resources to sync correctly. This pins the local setup kind clusters to
k8s v1.22.7 and crc version 1.40.0 uses k8s version v1.22.3+e790d7f
which work ok together.
=> Add crc local setup script

e2e/ingress_test.go, e2e/support/workspace.go
This follows up #37 and fix an issue in the API discovery check, when multiple GVKs are passed.
=> test: Fix API discovery check

docs/dns/health-checks.md, pkg/apis/kuadrant/v1/types.go, pkg/cluster/mapper.go, pkg/dns/aws/dns.go, pkg/dns/aws/health.go, pkg/dns/dns.go, pkg/dns/health.go, pkg/reconciler/dns/dns_record.go, pkg/reconciler/dns/health.go, pkg/reconciler/ingress/ingress.go, pkg/util/metadata/annotations.go
Adds the ability for users to set an annotation in the Ingress object that will result in health checks being reconciled for the endpoints.
>  ⚠️ The IP address specified in Route 53 health checks must be a public address. In order to verify this PR you need to use publicly accessible clusters
1. Start KCP and add the clusters to be used for verification
2. Start the kcp-glbc
```sh
source .env && ./bin/ingress-controller -kubeconfig .kcp/admin.kubeconfig -glbc-kubeconfig ./tmp/kcp-cluster-glbc-control.kubeconfig -dns-provider aws -domain sf.hcpapps.net
```
3. Create the sample resources
```sh
kubectl create namespace default
kubectl apply -n default -f samples/echo-service/echo.yaml
```
4. A service will be created and the workload propagated to the clusters. An Ingress object will be …
=> HCG-70: DNS Health checks

e2e/ingress_test.go, e2e/support/core.go, go.mod, go.sum, pkg/placement/placement.go, pkg/placement/placement_test.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/tls/secrets.go
Fixes #70 
This may be a temp fix depending on https://github.com/kcp-dev/kcp/issues/896
This also fixes an issue with closing a closed channel on the host watcher that was causing panics
Adds the placement label to ingress objects based on the placement label of the services the Ingress is targeting 
Update the Ingress e2e test to do the following
- create workspace
- create ns
- create deployment, ingress, service
- expect them to be scheduled to a workload cluster
- create another workload cluster
- schedule the ns to the new cluster
- expect everything to move to the new cluster
- validate the DNS entries are as expected
=> Add a workaround for placement not happening on ingress objects

samples/echo-service/echo.yaml
The kcp-glbc placement code is being removed in favour of the kcp
placement logic. Removing this so it doesn't interfere in the meantime.
Related to https://github.com/Kuadrant/kcp-glbc/pull/74
=> Remove kcp.dev/placement annotation from sample

pkg/reconciler/ingress/ingress.go
targets length is no longer the total number of ips, so cant be used to initialize the slice.
=> Fix panic when ips > 1 for ingress

cmd/kcp-glbc/main.go, config/manager/manager.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, pkg/reconciler/tls/controller.go, pkg/reconciler/tls/secrets.go, pkg/tls/cert_manager.go, pkg/util/env/env.go
Fixes #102.
It relies on the Downward API to retrieve the Deployment namespace. It also skips starting the informer that watches for TLS Secrets, when TLS certificate is disabled, to avoid the work-queue to keep growing, as items are not consumed.
Incidentally, this enables changing the current ClusterRole for a Role, to avoid RW cluster-wide permissions for Secrets and Certificates, that may be considered too broad to meet some security models.
=> Co-locate cert-manager resources in kcp-glbc namespace

pkg/reconciler/controller.go, pkg/reconciler/ingress/controller.go
This fixes an issue where an object reconciliation reaches the maximum number of retries (hard-coded to 5), and the object is dropped, because changes are queued via the default rate limiter, which assumes each re-queue follows an error. Enqueuing objects via the default rate limiter should only be done after a reconciliation error. 
This happens when optimistic locking fails, and also with the host watcher, which often leads to reaching that limit.
=> Do not use rate limiter when enqueuing objects

cmd/kcp-glbc/main.go, docs/observability/logging.adoc, go.mod, go.sum, pkg/cluster/mapper.go, pkg/dns/aws/dns.go, pkg/dns/aws/health.go, pkg/dns/dns.go, pkg/dns/health.go, pkg/log/flags.go, pkg/log/kcp.go, pkg/log/logger.go, pkg/log/zap.go, pkg/metrics/server.go, pkg/net/hostresolv.go, pkg/net/watch.go, pkg/placement/placement.go, pkg/reconciler/controller.go, pkg/reconciler/deployment/controller.go, pkg/reconciler/dns/controller.go, pkg/reconciler/dns/dns_record.go, pkg/reconciler/dns/health.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/tracker.go, pkg/reconciler/service/controller.go, pkg/reconciler/tls/controller.go, pkg/reconciler/tls/secrets.go
This PR introduces structured logging, by using Zap as logging backend.
It binds Zap configuration to the CLI options, so that it's possible to set logging output either to `console` or `json`, e.g.:
```console
$ kcp-glbc --zap-encoder=json
{"level":"info","ts":1651568779.81949,"msg":"Creating TLS certificate provider","issuer":"glbc-ca"}
{"level":"info","ts":1651568780.865054,"logger":"kcp-glbc-dns","msg":"Creating DNS provider","provider":"aws"}
{"level":"info","ts":1651568781.389698,"logger":"kcp-glbc-dns","msg":"Using AWS DNS zone","id":"REDACTED"}
{"level":"info","ts":1651568781.690482,"logger":"kcp-glbc-dns","msg":"Starting workers"}
{"level":"info","ts":1651568781.690517,"logger":"kcp-glbc-service","msg":"Starting workers"}
{"level":"info","ts":1651568781.690476,"msg":"Started …
```
=> Structured logging

e2e/common.go, e2e/ingress_test.go, e2e/support/cluster.go, e2e/support/core.go, e2e/support/support.go, e2e/support/test.go, e2e/support/workspace.go, e2e/tls_test.go
This follows up #131, to apply the KCP syncer resources using client-go dynamic client, instead of spawning a `kubectl` command, when creating a WorkloadCluster in the e2e tests.
=> Apply KCP syncer resources using dynamic client

config/grafana/auth-proxy/grafana.yaml
The grafana operator requires the default admin user and basic auth to be enabled in order to reconcile dashboard resources.
Fixes https://github.com/Kuadrant/kcp-glbc/issues/142
=> Enable grafana basic auth

docs/observability/monitoring.adoc, e2e/metrics/metrics_test.go, pkg/reconciler/tls/controller.go, pkg/reconciler/tls/metrics.go, pkg/reconciler/tls/secrets.go, pkg/tls/metrics.go
This PR removes the `hostname` label from the TLS certificate metrics, except for the `glbc_tls_certificate_pending_request_count` metric.
This is a pre-requisite for #145.
=> Remove hostname label from TLS certificate metrics

config/kcp/glbc_role.yaml, config/kcp/glbc_role_binding.yaml, config/kcp/kustomization.yaml, config/kcp/namespace.yaml, config/kcp/service_account.yaml, utils/create_glbc_ns.sh
Add config to generate ns, role, role binding and sa for kcp/glbc user access.
Adds a script to create kcp/glbc namespace roles/role bindings and sa for a given user. Outputs a valid kubeconfig for the user.
=> Add kcp user roles

README.md
I've suggested some README updates based on trying to get a local dev environment setup.
Hopefully they make sense.
* Update the version of k8s that gets created, and say that it uses `kind` (I thought it needed `crc` and was confused when crc showed nothing running, then got further confused when debugging why podman was having trouble from `crc`, but was actually a problem with `kind`)
* Removed the cmd to run kcp-glbc locally as it's included in the make output, and is more accurate and means 1 less place to keep it up to date (was already out of date in the README)
* Updated the echo example to reference the actual sample file in the repo
* Removed unnecessary KUBECONFIG setting in cmds (it's instructed earlier to export it, so no need to set it for each cmd)
* Marked the section for …
=> Update README for local dev

config/observability/grafana/dashboards/glbc.yaml
Update the grafana dashboard "namespace" variable dropdown to remove hard coded options and current selection. Set refresh to 1 (On Dashboard Load).
Test locally with:
**Terminal 1:**
```
make local-setup
```
**Terminal 2:**
```
./utils/local-setup-deploy-glbc.sh
```
http://grafana.127.0.0.1.nip.io:8083
=> Update grafana dashboard ns dropdown

config/observability/grafana/dashboards/glbc.yaml
* Use instant on all targets
* Remove failed filter from total target
* Update "Total > 5m" target query
=> Grafana TLS panel fixes

config/observability/grafana/dashboards/glbc.yaml
There's a few changes here, so I'll list them and include some before & after screenshots:
* Filter the namespace dropdown to only list namespaces where a glbc is detected (based on the existence of the `glbc_controller_reconcile_total` metric)
* Organise the panels into 3 rows - AWS Route53, TLS & Pods
* Align graphs on each row for easier correlation
* Specify the metrics method used for each row i.e. [USE](https://www.brendangregg.com/usemethod.html#:~:text=The%20Utilization%20Saturation%20and%20Errors,identifying%20resource%20bottlenecks%20or%20errors.) or [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/)
* Set the y axis data types better (e.g. MiB, % etc..)
* Move the Cert issuer name out of the stat panel into a separate panel (avoids …
=> Organise the dashboard into rows, based on area & USE or RED method

config/observability/grafana/dashboards/glbc.yaml
Based on #165 (which should merge first and this PR rebased then).
Closes #107 
This change adds a 'Reconciliation and Workers' row with associated panels.
It also includes 1 new panel to show the number of goroutines, placed in the 'Pods' row.
Goroutines panel:
Reconciliation and Workers row:
=> Reconcile panels

e2e/support/deployment.go, e2e/support/dns.go, e2e/support/ingress.go, e2e/support/secret.go, e2e/support/service.go
This enables to report the stack traces in the assertion error messages more accurately.
=> chore(e2e): Mark support functions as test helper functions

e2e/ingress_test.go, pkg/reconciler/ingress/controller.go
This PR makes sure changes on the namespace, such as an update of the KCP cluster label,  `workloads.kcp.dev/cluster`, are reflected by the Ingress controller, into the Ingresses within that namespace.
It fixes a flake in the Ingress e2e test, where the following expectation is not consistently satisfied without the fix: https://github.com/Kuadrant/kcp-glbc/blob/1c6cdd748c5d1f1e9010b320b8ea35087e33e4b5/e2e/ingress_test.go#L127
=> fix: Enqueue Ingresses on Namespace updates

docs/observability/monitoring.adoc, e2e/metrics/metrics_test.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress.go, pkg/reconciler/ingress/metrics.go
Adds metrics around managed ingress objects 
~- glbc_ingress_managed_object_reconciliation(namespace, workspace, result, name)~
- glbc_ingress_managed_object_total ~(namespace, workspace)~
- glbc_ingress_managed_object_time_to_admission ~(namespace, workspace)~
**UPDATE**: We are removing the reconciliation metric (glbc_ingress_managed_object_reconciliation) as this can be achieved via the [controller metrics](https://github.com/Kuadrant/kcp-glbc/blob/main/docs/observability/monitoring.adoc#controller-metrics) and removing the `namespace` and `workspace` as we are trying to get a more global view for now.
Closes: https://github.com/Kuadrant/kcp-glbc/issues/106
1) Install GLBC locally 
`make local-setup`
2) Create an ingress object against KCP 
`kubectl apply -n default -f …
=> Ingress objects metrics

config/kcp/glbc-cluster-role.yaml
Add namespaces, required since https://github.com/Kuadrant/kcp-glbc/pull/177
=> Update glbc cluster role

pkg/reconciler/tls/controller.go, pkg/reconciler/tls/secrets.go
Pre-requisite for #194.
This fixes an infinite reconciliation loop in the Secret controller, where the Secret being reconciled is always updated and re-enqueued.
=> fix: Avoid updating TLS Secrets unnecessarily

config/observability/grafana/dashboards/glbc.yaml
This was a small oversight on my part I noticed when I went back to demo the dashboard.
The 2 time range graphs for route53 requests & tls certs should show a per second rate rather than the increase of the time range.
The change will result in much smaller numbers (as it's per second rates) on the 2 panels.
Tooltip text is also updated.
=> Use a rate for the graph showing time ranges

pkg/reconciler/dns/controller.go
This PR follows up #195 and #203, to fix #180.
The DNSRecord controller should only reconciler changes to the DNSRecord spec, and avoid re-enqueue the same DNSRecord after its status sub-resource has been updated.
=> fix: Do not enqueue DNSRecord when its generation hasn't incremented

.github/workflows/e2e.yaml, Makefile, e2e/metrics/metrics_test.go, e2e/support/dns.go
This PR follows up #194 to fix #180, by making sure we reach the final reconciliation state before asserting no spurious reconciliation occurs.
=> e2e: Wait for DNSRecord reconciliation before idling assertion

.github/workflows/e2e.yaml, e2e/metrics/metrics_test.go, e2e/metrics/support.go
This PR makes sure the metrics are correctly initialized at start time, before any processing has occurred.
=> e2e: Assert metrics are initialized

config/observability/grafana/dashboards/glbc.yaml
@jjaferson I've made a few tweaks from your PR #209 for you to review (I didn't want to just push to your PR branch without getting your take on them first).
- fix the percentile query to sum by the `le` label. If we don't do this, the query sums all buckets together and results in no percentiles at all (as no le labels were left in the result set to calculate percentiles with)
- add a right y axis that also shows the admission rate/s. The intention is to allow easier correlation between increases in percentiles and the rate of ingresses being admitted
- expanded the graph to show 3x percentiles i.e. 90, 95 & 99, to better catch outliers vs. a general increase across the board
- updated tooltip text to represent the above changes
- aligned the singlestat & graph with the panels below them …
=> Add admission rate & fix percentiles

docs/observability/generated_metrics.adoc, e2e/metrics/metrics_test.go, pkg/metrics/client_go_adapter.go, utils/prometheus_format_tables.csv
2 new metrics:
- rest_client_request_latency_seconds histogram
- rest_client_requests_total counter
TODO:
=> Closes #108. Enable metrics in client-go for rest requests

config/observability/grafana/dashboards/glbc.yaml
Depends on #206.
Shows metrics for REST calls to the KCP API.
3 new panels in a new row:
=> KCP api metrics panels

utils/local-setup.sh
Update the local setup script to create the `kcp-glbc` ns in the glbc
workspace so that the [default NAMESPACE env var ](https://github.com/Kuadrant/kcp-glbc/blob/main/config/deploy/local/controller-config.env.template#L10)value `kcp-glbc` will
always work. This is the ns where cert manager will create issuers and
certificates.
```
(export $(cat ./config/deploy/local/controller-config.env | xargs) && ./bin/kcp-glbc --kubeconfig .kcp/admin.kubeconfig --context system:admin)
```
=> Create kcp-glbc in glbc workspace

docs/observability/service_level_indicators_and_objectives.adoc
Closes #185.
It's probably easier to view this change in the adoc rich diff.
This proposal is deliberately for only 1 indicator and objective at this time.
It is focused on the primary job of the controller, and what the user really cares about i.e. an ingress being ready for use.
There is a separate follow up, #186 , to define some alert templates for the objective i.e. a 'symptom based alert'.
However, this doesn't preclude other [cause based alerts](https://docs.google.com/document/d/199PqyG3UsyXlwieHaqbGiWVa8eMWi8zzAn0YfcApr8Q/edit) being added (such as #187 , #188 , #189 ). They work hand in hand.
=> Add SLI/SLO proposal

config/rbac/cluster_role.yaml, config/rbac/cluster_role_binding.yaml, config/rbac/kustomization.yaml
Grant the GLBC controller access to APIExport resources and their content sub-resources.
Part of #237.
=> rbac: Add APIExport ClusterRole

pkg/reconciler/deployment/controller.go, pkg/reconciler/dns/controller.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/service/controller.go, pkg/reconciler/tls/controller.go
Currently, objects from the work queues are directly passed for reconciliation. This leads to polluting the work queues with staled objects in case of reconciliation errors, which breaks update event handlers on subsequent reconciliations / retries.
This PR makes sure objects copies are passed during reconciliation of objects from the work queues.
=> fix: Do not pollute working queues with staled objects

e2e/metrics/metrics_test.go, e2e/metrics/support.go
This PR is part of improving the stability of the metrics e2e test. It turns out the certificate issuance can be very quick when using the CA issuer, which leads to a duration that's rounded to zero.
=> e2e: TLS certificate issuance duration can be rounded to zero

pkg/reconciler/tls/secrets.go
This PR fixes the observation of the TLS certificate issuance duration metric, that is currently based on a staled Secret object when the Ingress update request fails because of conflicts. This PR makes sure the Secret object is the updated one.
=> fix: TLS certificate issuance duration on update conflicts

utils/create_glbc_ns.sh, utils/deploy.sh
The default value of MULTI_WORKSPACE_AWARE was changed to true to work correctly  with local-setup, but it wasn't possible to specify false. Can now be done with:
```
./utils/deploy.sh -m false
```
Removes the deletion of cluster roles and role bindings from `utils/create_glbc_ns.sh`
=> Allow multi cluster aware option to be set to false.

config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/kubernetes/monitoring_resources/rules-glbc.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/HighDNSLatencyAlert_test.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/HighDNSProviderErrorRate_test.yaml, config/observability/monitoring_resources/common/rules/HighDNSLatencyAlert.dhall, config/observability/monitoring_resources/common/rules/HighDNSProviderErrorRate.dhall, config/observability/monitoring_resources/common/rules/__glbc__.dhall, config/observability/openshift/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/openshift/monitoring_resources/rules-glbc.yaml, docs/observability/runbooks/HighDNSLatencyAlert.adoc, docs/observability/runbooks/HighDNSProviderErrorRate.adoc
Closes #189 
I created two alerts:
- Triggered when calls to the DNS Provider (AWS Route 53) have excessive errors or disconnections:
- The expression used for this divides the total errors by the total requests, giving us the error rate in percentage. At the moment, it is triggered when the error rate is higher than 1%.
- I created the appropriate unit tests to verify that it is working. In the test, there is an error rate of 2% which will be expected for the alert to be triggered.
- Triggered when calls to the DNS Provider (AWS Route 53) have high latency.
- The expression used for this divides the duration time in seconds by the total counted requests, giving us the latency rate. At the moment, it is triggered when the latency per request is greater than 0.5 seconds.
- I created the …
=> High DNS Errors Alerts

config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/kubernetes/monitoring_resources/rules-glbc.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/SLOIngressAdmissionLatency_test.yaml, config/observability/monitoring_resources/common/rules-glbc.dhall, config/observability/monitoring_resources/common/rules/SLOIngressAdmissionLatency.dhall, config/observability/monitoring_resources/dhall/AlertProperties/Type.dhall, config/observability/observability.mk, config/observability/openshift/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/openshift/monitoring_resources/rules-glbc.yaml, docs/observability/runbooks/SLOIngressAdmissionLatency.adoc
Closes #186 
* Adds 4 new alert rules (2x critical, 2x warning) for the initial Service Level Objective (SLO). 
* Adds unit tests for the alerts to cover short & long windows, and reset
* Adds a runbook for when one of these alerts fire <-- **START HERE FOR MORE CONTEXT ON SLO ALERTING** 
Although the practiced SLO in the early days of running this as a service will be lower than 99.9%, the alerts are set up as if it was 99.9%.
This is for 2 reasons:
* it provides a good indicator of how well we're doing on the objective against how we *want* to be before we're happy to offer it to users
* there is additional complexity in calculating the alert queries when the SLO is lower than 99.9% such that they are still useful. For example, if we used the recommended numbers in the [SRE …
=> Add SLO multi-window multi-burn rate alerts

cmd/kcp-glbc/main.go
Closes #299 
Scope the Cert Manager Informer to the target namespace.
Currently if you deploy the glbc using the manager service account it fails as it's trying to list certs at the cluster scope: 
```
2022-07-26T13:35:15.879Z ERROR cache/reflector.go:222 k8s.io/client-go@v0.0.0-20220524063253-5bb0eeecf2cf/tools/cache/reflector.go:167: Failed to watch *v1.Certificate: failed to list *v1.Certificate: certificates.cert-manager.io is forbidden: User "system:serviceaccount:kcp-glbc:kcp-glbc-controller-manager" cannot list resource "certificates" in API group "cert-manager.io" at the cluster scope
```
The following changes still need to be completed:
=> Scope the Cert Manager Informer to the target namespace.

config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/kubernetes/monitoring_resources/rules-glbc.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/HighTLSProviderErrorRate_test.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/HighTLSProviderLatencyAlert_test.yaml, config/observability/monitoring_resources/common/rules/HighTLSProviderErrorRate.dhall, config/observability/monitoring_resources/common/rules/HighTLSProviderLatencyAlert.dhall, config/observability/monitoring_resources/common/rules/__glbc__.dhall, config/observability/openshift/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/openshift/monitoring_resources/rules-glbc.yaml, docs/observability/runbooks/HighTLSProviderErrorRate.adoc, docs/observability/runbooks/HighTLSProviderLatencyAlert.adoc
Closes #191 
**Please note: PR #285 must be merged first before merging this PR**
I created two alerts:
- Triggered when calls to the TLS Provider (Let's Encrypt) have excessive errors or disconnections:
- The expression used for this divides the total errors by the total requests, giving us the error rate in percentage. At the moment, it is triggered when the error rate is higher than 1%.
- I created the appropriate unit tests to verify that it is working. In the test, there is an error rate of 2% which will be expected for the alert to be triggered.
- Triggered when calls to the TLS Provider (Let's Encrypt) have high latency.
- The expression used for this divides the duration time in seconds by the total counted requests, giving us the latency rate. At the moment, it is triggered when …
=> Tls certificate alerts

config/crd/bases/kuadrant.dev_dnsrecords.yaml, pkg/apis/kuadrant/v1/types.go, utils/kcp-contrib/apiresourceschema.yaml
Closes #315 
DNS Records were attempted to be created with no endpoints. Adds validations to the DNSRecord CRD to check that endpoints are not nil and has at minimum 1 item.
=> Add Endpoints validation to DNS Record

cmd/kcp-glbc/main.go, e2e/metrics/metrics_test.go, e2e/performance/ingress_test.go, pkg/reconciler/secret/controller.go, pkg/reconciler/secret/secret.go
Closes #309 
* Add a new reconciler for secrets to manage migration annotations
* Test with the migration sample.sh
=> Add secret reconciler to manage migration annotations

cmd/kcp-glbc/main.go, pkg/tls/cert_manager.go, pkg/tls/types.go
Closes #297 
* Perform check to TLS Issuer - Controller fails to start if the TLS issuer does not exist.
What is there now works. But, there might be a better way of doing this startup check.
=> Check on startup if TLS issuer exists

.github/workflows/e2e.yaml, utils/certman-issuer/ca.go, utils/certman-issuer/issuer.go, utils/certman-issuer/le.go, utils/deploy.sh, utils/local-setup.sh
Closes #304 
* Issuer script will only generate resources and specify an output directory for the yaml file.
* Issuer resources outputted in a single YAML file. We have an Issuer and a Secret kind.
* Updated local-setup and deploy scripts to make use and apply issuer.yaml file.
* Removed issuer namespace from metadata.
=> Cert issuer generates resources only

pkg/reconciler/dns/dns_record.go
Fix lint errors:
* SA1019: utilclock.Clock is deprecated: Use k8s.io/utils/clock.WithTickerAndDelayedExecution instead. (staticcheck)
=> Fix lint errors

.github/workflows/e2e.yaml
Closes #383 
Adding a new step to extract the Kind version from makefile and store it in evns to reuse in cluster setup. 
* e2e tests must pass
=> Extract kind version from Makefile

e2e/ingress_test.go, e2e/support/certificate.go, e2e/support/client.go, e2e/support/dns.go, e2e/support/ingress.go, pkg/access/reconcilers/certificate_reconciler.go, pkg/reconciler/ingress/ingress_reconciler.go, pkg/tls/cert_manager.go, samples/echo-service/echo.yaml
Closes #310 
stop reconciliation until the certificate is marked as ready. This means the DNS record will only be added once the certificate is ready. If there is no DNSRecord then traffic cannot access the Ingress.
There is a e2e test that checks the certificate is ready. 
Also you can watch it via kubectly 
```
k get ingress -A -w  -o jsonpath='{.metadata.annotations.kuadrant\.dev/certificate-status}'
```
```
k get DNSRecord -A -w
```
```
kubectl apply -f samples/echo-service/echo.yaml
```
You will see the status of the certificate always moves to ready before the DNSRecord is created.
Another test is to scale down cert-manager and create an ingress. With the above watches you will see the cert is requested but no DNSRecord is created even if the ingress syncs and is given a load …
=> prevent dns record from being created until after certificate ready

README.md, docs/deployment.md, docs/getting_started/tutorial.md, samples/location-api/sample.sh
Closes #365 
Update docs and location-api/sample.sh:
- Make use of home workspace in tutorial doc.
- Remove compute and user workspace from Readme.
- Add GLBC_EXPORT to deployment doc.
- Update location-api/sample.sh to make it work with the home workspace.
=> Update docs and location-api/sample.sh:

utils/local-setup-add-crc-cluster.sh, utils/local-setup.sh
Closes #395 
* Check to local-setup: if KUBECONFIG is set to `.kcp/admin.kubeconfig`, the script will exit and display a message.
Message: "Can NOT add physical clusters (kind) if KUBECONFIG is set to .kcp/admin.kubeconfig"
* Wondering if that message is okay or should I simply say: "KUBECONFIG can not be set to .kcp/admin.kubeconfig".
* Check is placed after KCP is attempting to start so I could use the cleanup() exit function.
=> Check valid KUBECONFIG in local-setup

config/observability/kubernetes/grafana_patch.yaml
Closes #427 
Initially, I tried just changing the [kube-prometheus version](https://github.com/Kuadrant/kcp-glbc/blob/cc2b91dd873caac18da89a09307417cac0c66fb6/config/kube-prometheus/kustomization.yaml#L4), but I was getting a few errors and kube-state-metrics and other deployments were failing to become ready.
- I noticed there was already a grafana_patch.yaml file created. I used the same file to add the necessary patches to change the Grafana version to the same as our shared Grafana.
- I tested it locally and it seems to be working perfectly. Panels are working correctly. When creating new panels, the JSON model remains very similar from the shared Grafana dashboard which is good to avoid problems when merging any changes.
=> Patch local Grafana deployment version

config/apiexports/apibinding/glbc-apibinding.yaml
* The group field is redundant as it's an empty string. This causes a diff to always show up when comparing the APIBinding in a cluster with the version in the repo (e.g. what ArgoCD does to determine if an application is in sync)
=> Remove redundant group field from APIBinding

config/observability/kubernetes/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/kubernetes/monitoring_resources/rules-glbc.yaml, config/observability/kubernetes/monitoring_resources/rules_unit_tests/CertManagerDown_test.yaml, config/observability/monitoring_resources/common/rules/CertManagerDown.dhall, config/observability/monitoring_resources/common/rules/__glbc__.dhall, config/observability/openshift/monitoring_resources/rules-glbc-prometheusrule.yaml, config/observability/openshift/monitoring_resources/rules-glbc.yaml, docs/observability/runbooks/CertManagerDown.adoc, docs/observability/runbooks/HighTLSProviderErrorRate.adoc, docs/observability/runbooks/HighTLSProviderLatencyAlert.adoc
Closes #402 
- Add alert which is triggered when cert-manager is down, fails to become ready, or does not exist.
- Add runbook doc for troubleshooting ideas if alert is triggered.
- Add unit tests to alert.
- Updated commands in two runbooks (TLS alerts runbooks) as the namespace for cert-manager has changed.
=> Add alert, triggered when cert-manager is down:

docs/observability/monitoring_resources.adoc
Closes #432 
- Added to [monitoring resources](https://github.com/kcp-dev/kcp-glbc/blob/main/docs/observability/monitoring_resources.adoc) document, how to add a new alert rule (to Openshift only).
=> Add to doc - How to add a new alert rule (to Openshift only)

Makefile, README.md, samples/echo-service/echo.yaml, utils/local-setup-add-crc-cluster.sh, utils/local-setup.sh
Adds an option to local-setup to use a CRC cluster to back the default sync target (kcp-cluster-1) instead of kind.
```
make local-setup USE_CRC=true
```
=> Add crc option to local setup

.github/workflows/kcp-glbc-image.yaml
Update glbc image github action to reference the correct github repository owner, kcp-dev instead of kuadrant.
=> Fix glbc image github action

.github/workflows/smoke.yaml, test/smoke/basic_ingress.go, test/support/namespace.go, test/support/support.go, test/support/workspace.go
Closes #444 
Adds a GitHub action to run the smoke test against the stable environment.
Update the name generate function used for resources in smoke and performance tests so they are shorter and more meaningful. Uses the same GenerateName function from k8s
=> Add smoke test GH action

.github/workflows/kcp-glbc-image.yaml
Removes the updated deployment logic that was changed on the release branch.
=> Update kcp-glbc-image action from main

.github/workflows/performance.yaml, .github/workflows/smoke.yaml, Makefile, test/smoke/ingress_test.go
Add environment as input to smoke and performance test GH Actions allowing them to be executed against any environment configured in GitHub. Also add concurrency to ensure that only one instance of either the smoke or performance tests are running in any environment at any time.
Adds a schedule to the smoke test, currently configured to run twice a day at 06:13 and 18:13, to try and avoid times that would have a high likelihood of failing to due to demand.
Rename smoke test and job name and allow specifying tags on the smoke test build to narrow scope as required. Currently we only have a single ingress test but more could be added later and run as independent jobs in the smoke test run.
Add make target to generate test oidc kubeconfig
```
make generate-test-oidc-kubeconfig
```
=> Update smoke and perf test GH actions

config/observability/monitoring_resources/openshift/GLBCInstanceDown.dhall, config/observability/openshift/monitoring_resources/GLBCInstanceDown.yaml, config/observability/openshift/monitoring_resources/rules-hcg-prometheusrule.yaml, config/observability/openshift/monitoring_resources/rules-hcg.yaml, config/observability/openshift/monitoring_resources/rules_unit_tests/GLBCInstanceDown_test.yaml
- Removed from alert and unit test the check for the label_glbc_name = "kcp-unstable-redhat-hcg", to stop the alert from firing unnecessarily.
=> Remove from alert the check on the absence of "kcp-unstable-redhat-hcg"

utils/local-setup-add-crc-cluster.sh, utils/local-setup.sh
Add -r (--no-run-if-empty) flag to xargs command to ensure it doesn't run if no kcp namespaces are found.
* Delete any existing crc cluster `crc  delete`
* Run setup using crc `make local-setup USE_CRC=true`
=> Fix cleanup of kcp resources on fresh crc cluster

README.md, docs/deployment.md, docs/getting_started/overview.md, docs/observability/runbooks/glbctargetdown.adoc
Closes #479 
- Some formatting fix in our Readme doc. It wasn't showing the text as a sub-title.
- Typos: GBLC to GLBC
- Some dead links to `kcp` docs found and updated.
=> Update dead links, typo fixes, and formatting fix.

pkg/_internal/util/math/hash.go, pkg/_internal/util/math/hash_test.go, pkg/apis/kuadrant/v1/types.go, pkg/apis/kuadrant/v1/types_test.go, pkg/dns/verification_test.go
Closes #447 
- Added two functions containing an algorithm to hash the domain verification token. I moved these hashing functions to the util directory as this function is a generic one which will hash any given string. + added unit test for hash function.
- Updated the GetToken() function to return a hashed value of the domain verification token. + added unit test.
- Updated tests to not expect a workspace value.
=> Hash Domain Verification Token value + Unit Test

pkg/reconciler/ingress/ingress_reconciler.go, pkg/reconciler/route/route_reconciler.go, pkg/traffic/host.go, pkg/traffic/ingress.go, pkg/traffic/ingress_test.go, pkg/traffic/traffic.go, test/e2e/ingress_test.go, test/smoke/basic_ingress.go, test/support/ingress.go
Closes #
ensures that if an ingress has a spec with a glbc generated host that matches the generated host for that ingress, that it is left in the spec
I am looking at adding unit tests as we don't have any coverage of this method currently
The following changes still need to be completed:
*
=> add fix for existing ingresses that have existing specs

config/crd/bases/kuadrant.dev_dnsrecords.yaml, config/kcp-contrib/apiresourceschema.yaml, pkg/apis/kuadrant/v1/types.go, pkg/dns/aws/dns.go, pkg/reconciler/ingress/ingress_reconciler.go, pkg/reconciler/route/route_reconciler.go, pkg/traffic/dns.go, pkg/traffic/dns_test.go, pkg/traffic/errors.go, pkg/traffic/host.go, pkg/traffic/host_test.go, pkg/traffic/ingress.go, pkg/traffic/ingress_test.go, pkg/traffic/route.go, pkg/traffic/tls.go, pkg/traffic/traffic.go, test/e2e/ingress_test.go, test/e2e/metrics/metrics_test.go, test/smoke/basic_ingress.go, test/support/ingress.go
Closes #412 
* Moving generated hos annotation to the DNSrecord CR so the user won't have the option to mess with it in the future
* e2e tests on the PR should prove the functionality of the change. 
*  check custom domains are working as expected.
=> gh-412 move generated host annotation got dns record

.vscode/launch.json
* Add VS Code debugging configuration to debug e2e tests
* Locally, prepare the environment for e2e tests
```sh
make local-setup
(export $(cat ./config/deploy/local/kcp-glbc/controller-config.env.ci | xargs) && \
KUBECONFIG=./tmp/kcp.kubeconfig ./bin/kcp-glbc)
```
* On VS Code, set a breakpoint in the e2e code and start debugging with the `Launch e2e tests` profile
* Verify that the e2e tests start and run as expected, and execution stops at the breakpoint
=> e2e debugging configuration for VS Code

pkg/traffic/dns_test.go
Closes #511 
- Unit Test: testing it wraps the object passed in an ExplicitKey object and returns it (For Ingress and Routes).
=> Unit Test on the objectKey function

go.mod, go.sum, pkg/dns/aws/dns.go, pkg/dns/dns_record.go, pkg/reconciler/ingress/controller.go, pkg/reconciler/ingress/ingress_reconciler.go, pkg/reconciler/route/controller.go, pkg/reconciler/route/route_reconciler.go, pkg/traffic/dns.go, pkg/traffic/ingress.go, pkg/traffic/route.go, pkg/traffic/traffic.go, test/e2e/metrics/metrics_test.go, test/support/route/route.go
Closes #496 
When the DNSRecord appears published, we check that the DNSLBHost has not yet been set, and that the DNSRecord has the status condition and that it has at least 1 endpoint. From this moment we attempt to dig the host against the nameservers but we don't get an IP address back immediately, so it would re-queue in 5 seconds, and then when it performs the dig again it returns an A record and IP address. After at least 1 A record is returned, we set the DNSLBHost.
- Check that DNSRecord for this ingress has the status condition. For this I had to export the function `RecordIsAlreadyPublishedtoZone` to use it.
- Created HasDNSLBHost function as a check to ensure we do not go through the block of code if the DNSLBHost has already been set.
- Created GetCacheKey function in the …
=> Perform checks before setting the DNS LB host

pkg/apis/kuadrant/v1/types.go, pkg/dns/dns_record.go, pkg/traffic/dns.go, test/e2e/ingress_test.go, test/e2e/route_test.go, test/performance/dns_record_test.go, test/smoke/basic_ingress.go
Closes #506 
- Added a "DNSRecordSucceededConditionType" which means the record is available within a zone.
- Removed "DNSRecordFailedConditionType"
- The status "True" in a DNSRecord now means it has succeeded. (Previously the status "False" in a DNSRecord would mean it had succeeded)
=> Inverse "ProviderSuccess" condition in DNS record and on route and ingress tests
