kcp-dev/kcp-glbc

- Makefile
Ensure we always use the same version of controller gen (0.7.0)
> Fix controller gen version to 0.7.0

- pkg/reconciler/ingress/ingress.go
resolves and hosts A records and updates the DNSRecord CR. Tested against OSD and locally
> Resolve A records and update DNSrecord CR based on ingress load balancer

- .gitignore
- README.md
- utils/local-setup.sh
fixing a few issues I bumped into, setting up local KCP.
> local setup fixes

- Makefile
- utils/local-setup.sh
Rejigged local setup to allow for number of clusters as an argument. 
Makefile will still default to 2.
> support cluster_num argument

- README.md
This PR updates the readme to include the changes for the multi-leaf samples 
multi-leaf samples: https://github.com/Kuadrant/kcp-glbc/pull/15
> Updates readme to include multi-leaf samples

- utils/demo.sh
This is now merged https://github.com/kcp-dev/kcp/issues/45 and the demo doesn't really work with just 1 cluster.
> Add second cluster to demo script

- pkg/reconciler/dns/dns_record.go
- pkg/reconciler/ingress/controller.go
- pkg/reconciler/ingress/ingress.go
> Fix lint errors

- pkg/reconciler/deployment/controller.go
- pkg/reconciler/deployment/deployment.go
- pkg/reconciler/ingress/ingress.go
- pkg/reconciler/service/service.go
only use ingresses in the same namespace for dns records
> only use ingresses in the same namespace for dns records

- e2e/ingress_test.go
- e2e/support/deployment.go
- e2e/support/ingress.go
- e2e/support/service.go
This adapts the e2e tests and covers the happy path for the use cases introduced by #41.
> test: Use the new placement annotation

- pkg/reconciler/deployment/deployment.go
- pkg/reconciler/service/service.go
This fixes key collisions in the informer caches, that happen when the same objects are created in different workspaces, and which can be reproduced by running the e2e tests multiple times on the same KCP instance.
> fix: Use cluster-aware key to get objects

- config/rbac/role.yaml
Add create/update/delete permissions for cert manager certificates.
> Update rbac role

- pkg/net/watch.go
- pkg/reconciler/ingress/ingress.go
Follows up #103, making sure the stopped watcher is always removed from the list of watchers.
> Always remove watcher after being stopped

- Makefile
- e2e/ingress_test.go
- e2e/metrics/metrics_test.go
- e2e/support/configuration.go
- e2e/support/gomega.go
- e2e/support/support.go
- e2e/tls_test.go
- go.mod
- pkg/reconciler/tls/secrets.go
> Add metrics e2e test

- config/observability/grafana/dashboards/glbc.yaml
This PR adds new variables to choose the namespace and also new panels for resource usage and tls certificates
> add new panels for tls certs and resource usage

- e2e/metrics/metrics_test.go
This PR fixes a race that can happen in the follow two calls during the execution of the metrics e2e test:
https://github.com/Kuadrant/kcp-glbc/blob/6d80b134cfa58e140796baf94fdda55a208015d6/pkg/reconciler/ingress/ingress.go#L109-L116
> Fix race in metrics e2e test

- utils/local-setup-deploy-glbc.sh
and example install cmd for macOS
> Add check for timeout cmd

- e2e/metrics/metrics_test.go
This PR aims at mitigating the race that can happen in the metrics e2e test, where cert-manager is being too prompt to issue the TLS certificate (which turns out to be quick fast when using a CA issuer), and the pending TLS certificate request assertion runs too late.
> fix(e2e): Mitigate pending TLS certificate request assertion race

- e2e/metrics/metrics_test.go
> e2e: Check spurious reconciliation on idle

- .github/workflows/kcp-glbc-image.yaml
Automatically deploy the GLBC grafana dashboard on main branch updates.
> Auto deploy glbc grafana dashboard

- config/observability/grafana/dashboards/glbc.yaml
Swapping the description & queries for the dns singlestats and graphs
> Apply rate to the correct dashboard panels

- config/observability/grafana/dashboards/glbc.yaml
closes: https://github.com/Kuadrant/kcp-glbc/issues/105
> Adds dashboard for ingress metric

- utils/local-setup.sh
- utils/macos/required_brew_packages.sh
> add coreutils to required macos packages

- utils/local-setup.sh
Fixes https://github.com/Kuadrant/kcp-glbc/pull/221
> Create the kcp-glbc namespace in the correct workspace (root:default:kcp-glbc)

- cmd/kcp-glbc/main.go
small bit of doc to help clarify the use of the different clients
> add explanation for the context of each client

- README.md
This section can be helpful for people on-boarding in the future.
> Added a Troubleshooting section

- pkg/reconciler/tls/controller.go
This PR prevents reconciliation of Secrets that are not managed by the GLBC, and incidentally should stabilise the metrics e2e test.
> Only enqueue Secrets generated by cert-manager

- .github/workflows/e2e.yaml
Changes the e2e test to use the deploy script
Closes: https://github.com/Kuadrant/kcp-glbc/issues/196
> Changes the e2e test to use the deploy script

- pkg/reconciler/ingress/ingress.go
This PR removes the single patch and update requests made during Ingresses reconciliation, so only one update request is performed at the end of each reconciliation.
This reduces the number of conflicting updates, and possibly some missed updates, in addition to simplifying the reconciliation logic.
> fix: Batch Ingress updates

- config/observability/monitoring_resources/common/rules/__template__.dhall
- config/observability/observability.mk
Added an extra line so that it asks for the alert's expression as well, which then will be added to the alerting rule.
> Extra line to ask for an alert's expression

- pkg/reconciler/ingress/certificate_reconciler.go
- pkg/reconciler/ingress/controller.go
Closes #312
* See #312 
* Automated CI tests
> Only set essential labels and annotations on certificate request

- README.md
- docs/deployment.md
- docs/ingress/ingress-behavior.md
- docs/local_deployment.md
- docs/troubleshooting.md
- utils/local-setup-add-crc-cluster.sh
Update steps in README about how to run the e2e and performance tests locally.
> Docs update

- docs/proposals/assets/gateway-api/echo.yaml
- docs/proposals/assets/gateway-api/gatewayapi-binding.yaml
- docs/proposals/assets/gateway-api/gatewayapi-export.yaml
- docs/proposals/assets/gateway-api/gatewayapi-resources.yaml
- docs/proposals/assets/gateway-api/gatewayapi-with-hostname.yaml
- docs/proposals/assets/gateway-api/gatewayapi-without-hostname.yaml
- docs/proposals/assets/gateway-api/istio-controlplane-with-ingress.yaml
- docs/proposals/assets/gateway-api/istio-controlplane-without-ingress.yaml
- docs/proposals/assets/gateway-api/network-attachment-definition.crd.yaml
- docs/proposals/sync-gateway-api-resources.md
Proposal for Gateway APIs below.
More readable here: https://github.com/philbrookes/kcp-glbc/blob/2e9509b839f09f77692d91c2c092ad8a36ddedfd/docs/proposals/sync-gateway-api-resources.md
> Gateway apis

- utils/.setupEnv
- utils/deploy.sh
```
KUBECTL_KCP_BIN=~/go/bin/kubectl-kcp WAIT_WC_READY=true ./utils/deploy.sh -c none
```
> Allow overriding KUBECTL_KCP_BIN env var

- cmd/kcp-glbc/main.go
Closes #
adds an option to specify an api export name
> add option for glbc api export name

- docs/getting_started/overview.md
- docs/getting_started/tutorial.md
Closes #266 
* Add initial content for GLBC's installation (and verification)  and an overview on kcp
* Initial content for how to use the GLBC to provide ingress in a multi-cluster ingress scenario (kind clusters are fine initially)
The following changes still need to be completed:
> Add initial getting started guide

- docs/getting_started/overview.md
- docs/getting_started/tutorial.md
* Adding tutorial for GLBC using KCP 0.5
> Add Getting Started Guide KCP 0.5

- cmd/kcp-glbc/main.go
- pkg/reconciler/dns/controller.go
Closes #305 
- Logging all options
- Logging if AWS creds are set or not
> Log GLBC configuration

- pkg/reconciler/ingress/ingress_reconciler.go
- pkg/tls/cert_manager.go
our finalizers should be put under kuadrant.dev rather than kcp.dev
> change finalizer name to be namespaced with kuadrant.dev rather than kcp.dev

- Makefile
- docs/getting_started/overview.md
- docs/getting_started/tutorial.md
* Slight touch to the docs 
* Update of the kind version 
* Check if you can run it with a newer version of kind
> Docs and kind version

- .github/workflows/e2e.yaml
- Makefile
- README.md
- docs/deployment.md
- docs/getting_started/tutorial.md
- docs/local_deployment.md
- utils/deploy-observability.sh
- utils/deploy.sh
- utils/local-setup.sh
Closes #382 
* Removed the `kcp-cluster-glbc-control` 
* Reduced default number of kind clusters to 1
* Updated docs accordingly
* Go through the docs and ensure they reflect the current state of glbc 
* Test scripts to ensure they are working as expected
> less default clusters

- docs/observability/monitoring_resources.adoc
Closes #403 
* Documenting how to create a panel in Grafana and reflect those changes in our main dashboard.
> Document: add new panel to Grafana

- utils/local-setup.sh
move kcp to a different port so it does not collide with crc
> specify different port for KCP

- pkg/traffic/dns.go
Closes #397 
Ensuring health checks are working with routes. [Issue](https://github.com/kcp-dev/kcp-glbc/issues/397)
From the health check point of view, there is no difference between the Route and Ingress CR. However, checks used to be created alongside the Route\Ingress. This change allows the addition of checks to an existing object. 
To have a health check created in the AWS you must use a proper Openshift cluster. However, it should be sufficient to see the glbc attempting to create a check and failing because of the local IP passed in the check. 
1. run `make local-setup` 
2. run `./utils/local-setup-add-crc-cluster.sh` to create CRC cluster. 
3. Using the `.kcp/admin.kubeconfig` kubeconfig under the `root:kuadrant` workspace delete glbc API binding and API export: 
```
kubectl …
```
> gh-397 enable health checks on Route\Ingress update

- docs/release.md
Closes #494
Add docs detailing how to release GLBC stable to KCP stable.
> release docs

- .github/workflows/kcp-glbc-image.yaml
Closes #
*
The following changes still need to be completed:
*
> build and publish for release tags

- samples/location-api/sample.sh
Closes #517 
Changed the commands to get the annotation `kuadrant.dev/host.generated` from the dnsrecord instead of the ingress.
> Fix sample script display generated host
